document.addEventListener('DOMContentLoaded', function() {
    const languageList = document.querySelectorAll('#language-list li');
    const header = document.querySelector('header');

    // Datos de traducciones
    const translations = {
        en: {
            header: "Camera Movements",
            pan: "PAN",
            "pan-desc": "Horizontal movement on its axis",
            "pan-example": "\"Citizen Kane\" (1941) - Exploring Xanadu Mansion",
            tilt: "TILT",
            "tilt-desc": "Vertical movement to show height",
            "tilt-example": "\"Vertigo\" (1958) - Staircase in the Tower",
            zoom: "ZOOM",
            "zoom-desc": "Distance adjustment without moving the camera",
            "zoom-example": "\"Jaws\" (1975) - Dolly Zoom on the Beach",
            dolly: "DOLLY",
            "dolly-desc": "Physical movement forward or backward",
            "dolly-example": "\"The Shining\" (1980) - Hotel Hallways",
            truck: "TRUCK",
            "truck-desc": "Lateral movement parallel to the subject",
            "truck-example": "\"Goodfellas\" (1990) - Copacabana Entrance",
            pedestal: "PEDESTAL",
            "pedestal-desc": "Straight vertical movement",
            "pedestal-example": "\"2001: A Space Odyssey\" (1968) - Monolith",
            crane: "CRANE",
            "crane-desc": "Wide movement with a crane",
            "crane-example": "\"Gone with the Wind\" (1939) - Burning Atlanta",
            arc: "ARC",
            "arc-desc": "Circular movement around the subject",
            "arc-example": "\"The Matrix\" (1999) - Bullet Time",
            follow: "FOLLOW",
            "follow-desc": "Fluid subject tracking",
            "follow-example": "\"Children of Men\" (2006) - Ambush Scene",
            push: "PUSH",
            "push-desc": "Direct approach to the subject",
            "push-example": "\"Pulp Fiction\" (1994) - Uma Thurman’s Dance",
            pull: "PULL",
            "pull-desc": "Direct withdrawal from the subject",
            "pull-example": "\"The Godfather\" (1972) - Final Baptism",
            "whip-pan": "WHIP PAN",
            "whip-pan-desc": "Fast pan for transitions",
            "whip-pan-example": "\"Kill Bill\" (2003) - Scene Changes",
            handheld: "HANDHELD",
            "handheld-desc": "Unsteady handheld movement",
            "handheld-example": "\"The Blair Witch Project\" (1999) - Forest",
            steadicam: "STEADICAM",
            "steadicam-desc": "Stabilized tracking",
            "steadicam-example": "\"Rocky\" (1976) - Museum Stairs",
            "tracking-shot": "TRACKING SHOT",
            "tracking-shot-desc": "Long continuous shot",
            "tracking-shot-example": "\"Touch of Evil\" (1958) - Opening",
            reveal: "REVEAL",
            "reveal-desc": "Movement that uncovers something",
            "reveal-example": "\"Star Wars\" (1977) - Darth Vader Appears",
            "dutch-angle": "DUTCH ANGLE",
            "dutch-angle-desc": "Tilted angle for tension",
            "dutch-angle-example": "\"The Third Man\" (1949) - Vienna Streets",
            "over-the-shoulder": "OVER-THE-SHOULDER",
            "over-the-shoulder-desc": "View over the shoulder",
            "over-the-shoulder-example": "\"Casablanca\" (1942) - Intimate Dialogues",
            "rack-focus": "RACK FOCUS",
            "rack-focus-desc": "Focus shift between planes",
            "rack-focus-example": "\"The Graduate\" (1967) - Mrs. Robinson and Ben",
            boom: "BOOM",
            "boom-desc": "Vertical movement with a boom",
            "boom-example": "\"Titanic\" (1997) - Ship View",
            parallax: "PARALLAX",
            "parallax-desc": "Movement creating depth",
            "parallax-example": "\"The Lion King\" (1994) - Stampede Scene",
            spin: "SPIN",
            "spin-desc": "Full spin around the axis",
            "spin-example": "\"Inception\" (2010) - Dream Scenes"
        },
        es: {
            header: "Movimientos de Cámara",
            pan: "PAN",
            "pan-desc": "Movimiento horizontal sobre el eje",
            "pan-example": "\"Ciudadano Kane\" (1941) - Exploración de la Mansión Xanadu",
            tilt: "TILT",
            "tilt-desc": "Movimiento vertical para mostrar altura",
            "tilt-example": "\"Vértigo\" (1958) - Escalera en la Torre",
            zoom: "ZOOM",
            "zoom-desc": "Ajuste de distancia sin mover la cámara",
            "zoom-example": "\"Tiburón\" (1975) - Zoom Dolly en la Playa",
            dolly: "DOLLY",
            "dolly-desc": "Movimiento físico hacia adelante o atrás",
            "dolly-example": "\"El Resplandor\" (1980) - Pasillos del Hotel",
            truck: "TRUCK",
            "truck-desc": "Movimiento lateral paralelo al sujeto",
            "truck-example": "\"Goodfellas\" (1990) - Entrada al Copacabana",
            pedestal: "PEDESTAL",
            "pedestal-desc": "Movimiento vertical recto",
            "pedestal-example": "\"2001: Odisea del Espacio\" (1968) - Monolito",
            crane: "CRANE",
            "crane-desc": "Movimiento amplio con grúa",
            "crane-example": "\"Lo que el Viento se Llevó\" (1939) - Atlanta en Llamas",
            arc: "ARC",
            "arc-desc": "Movimiento circular alrededor del sujeto",
            "arc-example": "\"Matrix\" (1999) - Bullet Time",
            follow: "FOLLOW",
            "follow-desc": "Seguimiento fluido del sujeto",
            "follow-example": "\"Children of Men\" (2006) - Escena de la Emboscada",
            push: "PUSH",
            "push-desc": "Acercamiento directo al sujeto",
            "push-example": "\"Pulp Fiction\" (1994) - Baile de Uma Thurman",
            pull: "PULL",
            "pull-desc": "Alejamiento directo del sujeto",
            "pull-example": "\"El Padrino\" (1972) - Bautizo Final",
            "whip-pan": "WHIP PAN",
            "whip-pan-desc": "Paneo rápido para transiciones",
            "whip-pan-example": "\"Kill Bill\" (2003) - Cambio de Escenas",
            handheld: "HANDHELD",
            "handheld-desc": "Movimiento inestable a mano",
            "handheld-example": "\"La Bruja de Blair\" (1999) - Bosque",
            steadicam: "STEADICAM",
            "steadicam-desc": "Seguimiento estabilizado",
            "steadicam-example": "\"Rocky\" (1976) - Escaleras del Museo",
            "tracking-shot": "TRACKING SHOT",
            "tracking-shot-desc": "Plano secuencia largo",
            "tracking-shot-example": "\"Touch of Evil\" (1958) - Apertura",
            reveal: "REVEAL",
            "reveal-desc": "Movimiento que descubre algo",
            "reveal-example": "\"Star Wars\" ( W7) - Darth Vader Aparece",
            "dutch-angle": "DUTCH ANGLE",
            "dutch-angle-desc": "Ángulo inclinado para tensión",
            "dutch-angle-example": "\"El Tercer Hombre\" (1949) - Calles de Viena",
            "over-the-shoulder": "OVER-THE-SHOULDER",
            "over-the-shoulder-desc": "Vista sobre el hombro",
            "over-the-shoulder-example": "\"Casablanca\" (1942) - Diálogos Íntimos",
            "rack-focus": "RACK FOCUS",
"a": "Cambio de enfoque entre planos",
            "rack-focus-example": "\"El Graduado\" (1967) - Mrs. Robinson y Ben",
            boom: "BOOM",
            "boom-desc": "Movimiento vertical con pluma",
            "boom-example": "\"Titanic\" (1997) - Vista del Barco",
            parallax: "PARALLAX",
            "parallax-desc": "Movimiento que crea profundidad",
            "parallax-example": "\"El Rey León\" (1994) - Escena del Desfiladero",
            spin: "SPIN",
            "spin-desc": "Giro completo alrededor del eje",
            "spin-example": "\"Inception\" (2010) - Escenas de Sueños"
        },
        fr: {
            header: "Mouvements de Caméra",
            pan: "PAN",
            "pan-desc": "Mouvement horizontal sur son axe",
            "pan-example": "\"Citizen Kane\" (1941) - Exploration du Manoir Xanadu",
            tilt: "TILT",
            "tilt-desc": "Mouvement vertical pour montrer la hauteur",
            "tilt-example": "\"Vertigo\" (1958) - Escalier dans la Tour",
            zoom: "ZOOM",
            "zoom-desc": "Ajustement de la distance sans bouger la caméra",
            "zoom-example": "\"Les Dents de la Mer\" (1975) - Zoom Dolly sur la Plage",
            dolly: "DOLLY",
            "dolly-desc": "Mouvement physique en avant ou en arrière",
            "dolly-example": "\"Shining\" (1980) - Couloirs de l’Hôtel",
            truck: "TRUCK",
            "truck-desc": "Mouvement latéral parallèle au sujet",
            "truck-example": "\"Les Affranchis\" (1990) - Entrée au Copacabana",
            pedestal: "PEDESTAL",
            "pedestal-desc": "Mouvement vertical droit",
            "pedestal-example": "\"2001 : L’Odyssée de l’Espace\" (1968) - Monolithe",
            crane: "CRANE",
            "crane-desc": "Mouvement large avec une grue",
            "crane-example": "\"Autant en Emporte le Vent\" (1939) - Atlanta en Feu",
            arc: "ARC",
            "arc-desc": "Mouvement circulaire autour du sujet",
            "arc-example": "\"Matrix\" (1999) - Bullet Time",
            follow: "FOLLOW",
            "follow-desc": "Suivi fluide du sujet",
            "follow-example": "\"Les Fils de l’Homme\" (2006) - Scène d’Embuscade",
            push: "PUSH",
            "push-desc": "Approche directe du sujet",
            "push-example": "\"Pulp Fiction\" (1994) - Danse d’Uma Thurman",
            pull: "PULL",
            "pull-desc": "Éloignement direct du sujet",
            "pull-example": "\"Le Parrain\" (1972) - Baptême Final",
            "whip-pan": "WHIP PAN",
            "whip-pan-desc": "Panoramique rapide pour transitions",
            "whip-pan-example": "\"Kill Bill\" (2003) - Changements de Scènes",
            handheld: "HANDHELD",
            "handheld-desc": "Mouvement instable à la main",
            "handheld-example": "\"Le Projet Blair Witch\" (1999) - Forêt",
            steadicam: "STEADICAM",
            "steadicam-desc": "Suivi stabilisé",
            "steadicam-example": "\"Rocky\" (1976) - Escaliers du Musée",
            "tracking-shot": "TRACKING SHOT",
            "tracking-shot-desc": "Plan-séquence long",
            "tracking-shot-example": "\"La Soif du Mal\" (1958) - Ouverture",
            reveal: "REVEAL",
            "reveal-desc": "Mouvement qui révèle quelque chose",
            "reveal-example": "\"Star Wars\" (1977) - Apparition de Dark Vador",
            "dutch-angle": "DUTCH ANGLE",
            "dutch-angle-desc": "Angle incliné pour tension",
            "dutch-angle-example": "\"Le Troisième Homme\" (1949) - Rues de Vienne",
            "over-the-shoulder": "OVER-THE-SHOULDER",
            "over-the-shoulder-desc": "Vue par-dessus l’épaule",
            "over-the-shoulder-example": "\"Casablanca\" (1942) - Dialogues Intimes",
            "rack-focus": "RACK FOCUS",
            "rack-focus-desc": "Changement de mise au point entre plans",
            "rack-focus-example": "\"Le Lauréat\" (1967) - Mrs. Robinson et Ben",
            boom: "BOOM",
            "boom-desc": "Mouvement vertical avec perche",
            "boom-example": "\"Titanic\" (1997) - Vue du Navire",
            parallax: "PARALLAX",
            "parallax-desc": "Mouvement créant de la profondeur",
            "parallax-example": "\"Le Roi Lion\" (1994) - Scène du Canyon",
            spin: "SPIN",
            "spin-desc": "Tour complet autour de l’axe",
            "spin-example": "\"Inception\" (2010) - Scènes de Rêves"
        },
        it: {
            header: "Movimenti della Macchina da Presa",
            pan: "PAN",
            "pan-desc": "Movimento orizzontale sul proprio asse",
            "pan-example": "\"Quarto Potere\" (1941) - Esplorazione della Villa Xanadu",
            tilt: "TILT",
            "tilt-desc": "Movimento verticale per mostrare altezza",
            "tilt-example": "\"La Donna che Visse Due Volte\" (1958) - Scala nella Torre",
            zoom: "ZOOM",
            "zoom-desc": "Regolazione della distanza senza muovere la camera",
            "zoom-example": "\"Lo Squalo\" (1975) - Zoom Dolly sulla Spiaggia",
            dolly: "DOLLY",
            "dolly-desc": "Movimento fisico avanti o indietro",
            "dolly-example": "\"Shining\" (1980) - Corridoi dell’Hotel",
            truck: "TRUCK",
            "truck-desc": "Movimento laterale parallelo al soggetto",
            "truck-example": "\"Quei Bravi Ragazzi\" (1990) - Ingresso al Copacabana",
            pedestal: "PEDESTAL",
            "pedestal-desc": "Movimento verticale diritto",
            "pedestal-example": "\"2001: Odissea nello Spazio\" (1968) - Monolito",
            crane: "CRANE",
            "crane-desc": "Movimento ampio con gru",
            "crane-example": "\"Via col Vento\" (1939) - Atlanta in Fiamme",
            arc: "ARC",
            "arc-desc": "Movimento circolare attorno al soggetto",
            "arc-example": "\"Matrix\" (1999) - Bullet Time",
            follow: "FOLLOW",
            "follow-desc": "Seguito fluido del soggetto",
            "follow-example": "\"I Figli degli Uomini\" (2006) - Scena dell’Agguato",
            push: "PUSH",
            "push-desc": "Avvicinamento diretto al soggetto",
            "push-example": "\"Pulp Fiction\" (1994) - Ballo di Uma Thurman",
            pull: "PULL",
            "pull-desc": "Allontanamento diretto dal soggetto",
            "pull-example": "\"Il Padrino\" (1972) - Battesimo Finale",
            "whip-pan": "WHIP PAN",
            "whip-pan-desc": "Panoramica rapida per transizioni",
            "whip-pan-example": "\"Kill Bill\" (2003) - Cambio di Scene",
            handheld: "HANDHELD",
            "handheld-desc": "Movimento instabile a mano",
            "handheld-example": "\"The Blair Witch Project\" (1999) - Bosco",
            steadicam: "STEADICAM",
            "steadicam-desc": "Seguito stabilizzato",
            "steadicam-example": "\"Rocky\" (1976) - Scale del Museo",
            "tracking-shot": "TRACKING SHOT",
            "tracking-shot-desc": "Piano sequenza lungo",
            "tracking-shot-example": "\"L’Infernale Quinlan\" (1958) - Apertura",
            reveal: "REVEAL",
            "reveal-desc": "Movimento che scopre qualcosa",
            "reveal-example": "\"Star Wars\" (1977) - Apparizione di Darth Vader",
            "dutch-angle": "DUTCH ANGLE",
            "dutch-angle-desc": "Angolo inclinato per tensione",
            "dutch-angle-example": "\"Il Terzo Uomo\" (1949) - Strade di Vienna",
            "over-the-shoulder": "OVER-THE-SHOULDER",
            "over-the-shoulder-desc": "Vista sopra la spalla",
            "over-the-shoulder-example": "\"Casablanca\" (1942) - Dialoghi Intimi",
            "rack-focus": "RACK FOCUS",
            "rack-focus-desc": "Cambio di fuoco tra piani",
            "rack-focus-example": "\"Il Laureato\" (1967) - Mrs. Robinson e Ben",
            boom: "BOOM",
            "boom-desc": "Movimento verticale con asta",
            "boom-example": "\"Titanic\" (1997) - Vista della Nave",
            parallax: "PARALLAX",
            "parallax-desc": "Movimento che crea profondità",
            "parallax-example": "\"Il Re Leone\" (1994) - Scena della Fuga",
            spin: "SPIN",
            "spin-desc": "Giro completo attorno all’asse",
            "spin-example": "\"Inception\" (2010) - Scene dei Sogni"
        },
        de: {
            header: "Kamerabewegungen",
            pan: "PAN",
            "pan-desc": "Horizontale bewegung um die eigene achse",
            "pan-example": "\"Citizen Kane\" (1941) - Erkundung des Xanadu-Anwesens",
            tilt: "TILT",
            "tilt-desc": "Vertikale bewegung zur höhenanzeige",
            "tilt-example": "\"Vertigo\" (1958) - Treppe im Turm",
            zoom: "ZOOM",
            "zoom-desc": "Abstandsanpassung ohne kamerabewegung",
            "zoom-example": "\"Der Weiße Hai\" (1975) - Dolly-Zoom am Strand",
            dolly: "DOLLY",
            "dolly-desc": "Physische bewegung vorwärts oder rückwärts",
            "dolly-example": "\"Shining\" (1980) - Hotelgänge",
            truck: "TRUCK",
            "truck-desc": "Laterale bewegung parallel zum subjekt",
            "truck-example": "\"Goodfellas\" (1990) - Eingang ins Copacabana",
            pedestal: "PEDESTAL",
            "pedestal-desc": "Gerade vertikale bewegung",
            "pedestal-example": "\"2001: Odyssee im Weltraum\" (1968) - Monolith",
            crane: "CRANE",
            "crane-desc": "Weite bewegung mit kran",
            "crane-example": "\"Vom Winde Verweht\" (1939) - Brennendes Atlanta",
            arc: "ARC",
            "arc-desc": "Kreisförmige bewegung um das subjekt",
            "arc-example": "\"Matrix\" (1999) - Bullet Time",
            follow: "FOLLOW",
            "follow-desc": "Flüssiges verfolgen des subjekts",
            "follow-example": "\"Children of Men\" (2006) - Hinterhalt-Szene",
            push: "PUSH",
            "push-desc": "Direkte annäherung ans subjekt",
            "push-example": "\"Pulp Fiction\" (1994) - Tanz von Uma Thurman",
            pull: "PULL",
            "pull-desc": "Direktes zurückziehen vom subjekt",
            "pull-example": "\"Der Pate\" (1972) - Finale Taufe",
            "whip-pan": "WHIP PAN",
            "whip-pan-desc": "Schneller schwenk für übergänge",
            "whip-pan-example": "\"Kill Bill\" (2003) - Szenenwechsel",
            handheld: "HANDHELD",
            "handheld-desc": "Unstabile handbewegung",
            "handheld-example": "\"Blair Witch Project\" (1999) - Wald",
            steadicam: "STEADICAM",
            "steadicam-desc": "Stabilisierte verfolgung",
            "steadicam-example": "\"Rocky\" (1976) - Museumstreppen",
            "tracking-shot": "TRACKING SHOT",
            "tracking-shot-desc": "Lange ununterbrochene einstellung",
            "tracking-shot-example": "\"Im Netz der Leidenschaften\" (1958) - Eröffnung",
            reveal: "REVEAL",
            "reveal-desc": "Bewegung, die etwas enthüllt",
            "reveal-example": "\"Star Wars\" (1977) - Darth Vader Erscheint",
            "dutch-angle": "DUTCH ANGLE",
            "dutch-angle-desc": "Schräger winkel für spannung",
            "dutch-angle-example": "\"Der Dritte Mann\" (1949) - Wiener Straßen",
            "over-the-shoulder": "OVER-THE-SHOULDER",
            "over-the-shoulder-desc": "Blick über die schulter",
            "over-the-shoulder-example": "\"Casablanca\" (1942) - Intime Dialoge",
            "rack-focus": "RACK FOCUS",
            "rack-focus-desc": "Fokuswechsel zwischen ebenen",
            "rack-focus-example": "\"Die Reifeprüfung\" (1967) - Mrs. Robinson und Ben",
            boom: "BOOM",
            "boom-desc": "Vertikale bewegung mit ausleger",
            "boom-example": "\"Titanic\" (1997) - Schiffsansicht",
            parallax: "PARALLAX",
            "parallax-desc": "Bewegung, die tiefe schafft",
            "parallax-example": "\"Der König der Löwen\" (1994) - Schluchtszene",
            spin: "SPIN",
            "spin-desc": "Vollständige drehung um die achse",
            "spin-example": "\"Inception\" (2010) - Traumszenen"
        }
    };

    // Función para actualizar el idioma
    function updateLanguage(lang) {
        // Actualizar el título del header
        document.querySelector('h1').innerHTML = translations[lang].header;

        // Actualizar cada elemento con data-lang
        document.querySelectorAll('[data-lang]').forEach(element => {
            const key = element.getAttribute('data-lang');
            if (translations[lang][key]) {
                element.innerHTML = translations[lang][key];
            } else {
                console.warn(`No translation found for key "${key}" in language "${lang}"`);
            }
        });

        // Actualizar clase activa
        languageList.forEach(li => {
            li.classList.remove('active');
            if (li.getAttribute('data-lang') === lang) {
                li.classList.add('active');
            }
        });
    }

    // Evento para cambiar idioma
    languageList.forEach(li => {
        li.addEventListener('click', function() {
            const lang = this.getAttribute('data-lang');
            updateLanguage(lang);
        });
    });

    // Evento para detectar el scroll y cambiar los colores del header
    window.addEventListener('scroll', function() {
        if (window.scrollY > 50) { // Cambia los colores después de 50px de scroll
            header.classList.add('scrolled');
        } else {
            header.classList.remove('scrolled');
        }
    });

    // Inicializar en inglés
    updateLanguage('en');
});